# Generated by Django 5.0.6 on 2024-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$BfQd0h9o2YUS2garRxiNBj$0D9ValH0Mz186Vj9V92Z8g3A+DdBv/e1GdOcMuuWmFk=', max_length=255),
        ),
    ]
